Disable login button while processing logging in
stackinflow/focial pull request #48
Opened 2020-10-03 16:56 UTC by diegoalvis

Fix #25 

![video](https://user-images.githubusercontent.com/6097526/94997227-5fb2e380-056f-11eb-88fa-b1da28091cb5.gif)

2020-10-04 03:57 UTC, fayaz07 requested changes
Hi @diegoalvis , please use the `ViewState` instance rather than creating a new field there
also, when ViewState is `Busy`, all other views like `Email` field... should also be disabled

2020-10-06 23:32 UTC, diegoalvis commented
@fayaz07 done!

2020-10-07 04:40 UTC, fayaz07 approved these changes

2020-10-07 04:40 UTC, fayaz07 commented
@diegoalvis Thank you for your contribution :)

2020-10-07 04:40 UTC, merged