Solve all linters, mute print only
stackinflow/focial pull request #59
Opened 2020-10-10 17:47 UTC by maplerichie

Fixed all linter warnings.
Except `print()`
```dart
include: package:lint/analysis_options.yaml
linter:
  rules:
    avoid_print: false
```

2020-10-11 03:05 UTC, fayaz07 commented
did you build the project with xcode? I can see a `Podfile` there

2020-10-11 03:20 UTC, fayaz07 commented on analysis_options.yaml
> +linter:
remove exception for print
and please replace `print` with `debugPrint`

2020-10-11 03:31 UTC, fayaz07 approved these changes

2020-10-11 03:32 UTC, fayaz07 requested changes
please remove the print exception and replace them with `debugPrint`

2020-10-11 05:28 UTC, maplerichie commented
> did you build the project with xcode? I can see a `Podfile` there

Nope, I code and build on iOS, generated by default.

Will create a new pull request with some changes.

2020-10-11 06:27 UTC, fayaz07 commented
@maplerichie you could have done those other changes in some other PR

2020-10-11 06:28 UTC, fayaz07 approved these changes

2020-10-11 06:28 UTC, merged

2020-10-14 03:08 UTC, maplerichie commented
> @maplerichie you could have done those other changes in some other PR

Discover some minor issues when solving linters, thus solve them along.
Thanks